sudo: required
service:
    - docker
    
before_install:
    - docker build -t sergei/docker-react -f Docker.dev .
    
script:
    - docker run -e CI=true sergei/docker-react npm run test -- --coverage
