version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Docker.dev
    ports:
       - "3000:3000"
    volumes:
       - /app/_modules
       - .:/app
  tests:
    build:
      context: .
      dockerfile: Docker.dev
    volumes:
      - /app/_modules
      - .:/app
    command: ["npm", "run", "test"]


